[general]
use_middle_proxy = false
log_level = "normal"

[general.modes]
classic = false
secure = false
tls = true

[server]
port = 3128

[[server.listeners]]
ip = "0.0.0.0"

[censorship]
tls_domain = "storage.googleapis.com"  # домен для маскування
mask = true
tls_emulation = true


[access.users]
andrii = "8f80ef9d43d31b1189c20395fddddc7c"

[general.links]
show = "*"
public_host = "192.168.1.65"  # IP твого Pi
public_port = 3128
