tap "caskroom/cask"
tap "homebrew/bundle"
tap "buo/cask-upgrade"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"

# fonts
cask "font-hack-nerd-font"
cask "font-fira-code"
cask "font-martian-mono"
cask "font-monaspace"

# languages and tools
brew "tokei"
brew "fnm"
brew "go"
brew "maven"
brew "pyenv"
brew "coreutils"

# chat
cask "signal"
cask "telegram"
cask "viber"

# mac specific
brew "mas"
cask "rectangle"
cask "stats"
cask "hammerspoon"
cask "karabiner-elements"
cask "monitorcontrol"
cask "raycast"
cask "alt-tab"
cask "little-snitch"
cask "bartender"
cask "contexts"
cask "little-snitch"

# git
brew "difftastic"
brew "gh"
brew "git-quick-stats"
brew "onefetch"

# api
brew "hurl"
cask "bruno"
cask "postman"

# terminal
cask "iterm2"
brew "curl"
brew "fd"
cask "session-manager-plugin"
brew "neofetch"

# media
cask "obs"
cask "eagle"
cask "flameshot"
cask "zoom"
cask "vlc"
cask "spotify"
cask "qview"

# files
cask "commander-one"
brew "rclone"
brew "rsync"
cask "insync"
cask "sublime-merge"
cask "sublime-text"
cask "visual-studio-code"
cask "obsidian"

# misc
brew "nginx", restart_service: true
brew "postgresql@14"
brew "scrcpy"
brew "redis"
cask "another-redis-desktop-manager"
cask "dbeaver-community"
cask "switchhosts"
cask "vivaldi"
cask "wkhtmltopdf"
cask "raspberry-pi-imager"

vscode "astro-build.astro-vscode"
vscode "bbenoist.nix"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-github-actions"
vscode "gruntfuggly.todo-tree"
vscode "humao.rest-client"
vscode "jock.svg"
vscode "kisstkondoros.vscode-codemetrics"
vscode "me-dutour-mathieu.vscode-github-actions"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "p1c2u.docker-compose"
vscode "quentinguidee.gitignore-ultimate"
vscode "redhat.vscode-yaml"
vscode "ryu1kn.partial-diff"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "takumii.markdowntable"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "unifiedjs.vscode-mdx"
vscode "vitest.explorer"
vscode "wakatime.vscode-wakatime"
vscode "kejun.markdown-alert"
