tap "buo/cask-upgrade"

# fonts
cask "font-jetbrains-mono" # used in obsidian
cask "font-jetbrains-mono-nerd-font" # used in iterm2 form icons
cask "font-hack-nerd-font" # used in vscode terminal
cask "font-fira-code"
cask "font-martian-mono"
cask "font-monaspace"
cask "font-cascadia-code"

# languages and tools
brew "fnm" # Node.js version manager (installs prebuild binary)
brew "nvm" # for work
brew "bun"
brew "go"
brew "maven" # for work
brew "pyenv" # Python version management
brew "coreutils"

# mac specific
brew "mas" # Mac App Store command line interface
cask "swiftbar" # custom menu bar programs
cask "rectangle" # Move and resize windows in macOS using keyboard shortcuts or snap areas
cask "stats" # system monitor in your menu bar
cask "lunar" # displays brightness
cask "hammerspoon" # automation of macOS (required by rcmd)
cask "bartender" # Hides menu bar icons
cask "contexts" # better Command-Tab
cask "little-snitch" # network monitoring
cask "processspy" # aggregate memory usages by process
cask "pearcleaner" # app cleaner
cask "karabiner-elements" # keyboard customizer for tilda in EU magic keyboard
cask "logi-options+" # to set smooth scroll for mx master mouse
cask "orbstack" # docker client
cask "lookaway" # break time reminder app
cask "timing" # automatic time and productivity tracking app

# git
brew "git" # fresh and faster than default installed
brew "gh" # github cli
brew "difftastic" # a structural diff that understands syntax
brew "git-quick-stats" # access various statistics in git repository
brew "tokei" # show the number of files, total lines within those files and code, comments
brew "lazygit" # terminal UI for git
cask "sublime-merge"

# editors
brew "neovim"
# brew "neovide" # Neovim GPU Client (smooth, animation) (miss app in application folder)
brew "micro" # editor
cask "sublime-text"
cask "visual-studio-code"
cask "zed"
cask "zed@preview"

# api
cask "bruno" # local first API testing
cask "postman"

# dev / cloud
cask "claude-code@latest" # tracks latest release; plain `claude-code` lags
brew "curl"
cask "session-manager-plugin" # aws

# terminal
cask "iterm2" # main terminal (supports nerd fonts unlike default mac terminal)
cask "ghostty" # fast but i need search

# terminal cli
brew "fzf" # fuzzy finder (use **<TAB> for completion)
brew "fd" # fd is a program to find entries in your filesystem
brew "ripgrep" # searches for text inside files across directories
brew "television" # fuzzy finder for the terminal
brew "bat" # cat alternative
brew "eza" # ls alternative
brew "sheldon" # shell plugin manager
brew "stow" # symlink farm manager
brew "yt-dlp" # command-line audio/video downloader
brew "jq" # command-line JSON processor
brew "zoxide" # a smarter cd command
brew "starship" # prompt for shel
brew "fastfetch" # neofetch like system information tool

# media
cask "obs"
cask "eagle" # organize photos
cask "zoom"
cask "vlc"
cask "pika" # colour picker
cask "cleanshot" # screenshot tool with self-timer and ocr

# audio
cask "spotify"
cask "loopback" # Cable-free audio routing
cask "soundsource" # sound control per app
cask "audio-hijack" # recording
brew "cava" # cross-platform audio visualizer

# files, notes
cask "commander-one" # file manager with dual-pane interface
brew "rsync" # file copying tool for both remote and local files
cask "insync" # Google Drive, OneDrive, and Dropbox sync
cask "obsidian" # personal notes, journaling, knowledge bases, and project management,

# database, services
brew "redis"
brew "sqlite"
brew "postgresql@14"
brew "nginx", restart_service: true
cask "another-redis-desktop-manager"
cask "dbeaver-community" # cross-platform database tool
cask "tableplus" # database management
cask "db-browser-for-sqlite"

# browsers
cask "google-chrome" # for work
cask "microsoft-edge" # personal browser with pinned tabs not being scrollable in vertical view
cask "vivaldi" # emoji doesn't woks
cask "firefox"
cask "firefox@developer-edition" # use sometimes with sidebery

# chat
cask "telegram"
cask "viber"
cask "signal"

# misc
cask "espanso" # text expander
brew "scrcpy" # display and control your Android device
cask "wkhtmltopdf" # for work
# cask "raspberry-pi-imager"

# ------------------------------------------------------------------------------
#  VSCode extensions
# ------------------------------------------------------------------------------
# git
vscode "eamodio.gitlens"
vscode "quentinguidee.gitignore-ultimate"
vscode "ryu1kn.partial-diff"
# github
vscode "github.vscode-github-actions"
vscode "github.copilot-chat"
# files
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "redhat.vscode-yaml"
vscode "jock.svg"
# javascript
vscode "dbaeumer.vscode-eslint"
vscode "vitest.explorer"
vscode "bradlc.vscode-tailwindcss"
vscode "esbenp.prettier-vscode"
# vscode "kisstkondoros.vscode-codemetrics"
# docker
vscode "docker.docker" # Docker DX: Dockerfile/compose language support
vscode "ms-azuretools.vscode-containers" # Container Tools: explorer, run/debug
vscode "p1c2u.docker-compose"
# python
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "detachhead.basedpyright"
vscode "ms-python.vscode-python-envs"
# markdown
vscode "kejun.markdown-alert"
vscode "bierner.github-markdown-preview"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bierner.markdown-yaml-preamble"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-checkbox"
vscode "takumii.markdowntable"
vscode "renathossain.markdown-runner" # run js in markdown
vscode "unifiedjs.vscode-mdx"
vscode "stateful.runme" # run js in markdown like in Notebooks
# misc
vscode "ms-vscode-remote.remote-ssh" # remote Development via ssh
vscode "astro-build.astro-vscode"
vscode "gruntfuggly.todo-tree"
vscode "humao.rest-client"
vscode "wakatime.vscode-wakatime"
vscode "qwtel.sqlite-viewer"
vscode "bruno-api-client.bruno"
# vscode "streetsidesoftware.code-spell-checker"
vscode "usernamehw.errorlens"
vscode "pomdtr.excalidraw-editor"

# ------------------------------------------------------------------------------
# App Store applications
# ------------------------------------------------------------------------------
mas "Home Assistant", id: 1099568401
mas "rcmd", id: 1596283165 # Switch apps instantly using the ⌘ Right Command key
mas "Velja", id: 1607635845 # browser picker
mas "DaisyDisk", id: 411643860
mas "Dato", id: 1470584107 # time zone travel
mas "Amphetamine", id: 937984704 # enable mac to stay awake on battery with the lid closed while an external display is connected

