apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-ha
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: homeassistant
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    isDefault: true
    editable: true
